//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.3053.
// 
namespace PalletScanMobile.WebRefFGSync {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IFGSyncService", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Delegate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XppObjectBase))]
    public partial class FGSyncService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public FGSyncService() {
            this.Url = "http://172.17.0.50/SyncServicesTest184/FGSyncService.svc";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFGSyncService/ResetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public PalletEntity[] ResetData() {
            object[] results = this.Invoke("ResetData", new object[0]);
            return ((PalletEntity[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginResetData(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ResetData", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public PalletEntity[] EndResetData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((PalletEntity[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFGSyncService/GetFGYearInventory", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.InventCountingService")]
        public InventAvailContract[] GetFGYearInventory(int startId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool startIdSpecified) {
            object[] results = this.Invoke("GetFGYearInventory", new object[] {
                        startId,
                        startIdSpecified});
            return ((InventAvailContract[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetFGYearInventory(int startId, bool startIdSpecified, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetFGYearInventory", new object[] {
                        startId,
                        startIdSpecified}, callback, asyncState);
        }
        
        /// <remarks/>
        public InventAvailContract[] EndGetFGYearInventory(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((InventAvailContract[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFGSyncService/GetUserData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
        public UserData[] GetUserData() {
            object[] results = this.Invoke("GetUserData", new object[0]);
            return ((UserData[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserData(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserData", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public UserData[] EndGetUserData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((UserData[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFGSyncService/UpdateFGDesktop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateFGDesktop([System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")] PalletEntity[] dt, out long UpdateFGDesktopResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool UpdateFGDesktopResultSpecified) {
            object[] results = this.Invoke("UpdateFGDesktop", new object[] {
                        dt});
            UpdateFGDesktopResult = ((long)(results[0]));
            UpdateFGDesktopResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateFGDesktop(PalletEntity[] dt, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateFGDesktop", new object[] {
                        dt}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateFGDesktop(System.IAsyncResult asyncResult, out long UpdateFGDesktopResult, out bool UpdateFGDesktopResultSpecified) {
            object[] results = this.EndInvoke(asyncResult);
            UpdateFGDesktopResult = ((long)(results[0]));
            UpdateFGDesktopResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IFGSyncService/GetPing", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetPing() {
            object[] results = this.Invoke("GetPing", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetPing(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetPing", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndGetPing(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class PalletEntity {
        
        private decimal availableField;
        
        private bool availableFieldSpecified;
        
        private string batchNumberField;
        
        private string colorField;
        
        private string configField;
        
        private System.DateTime dateUpdatedField;
        
        private bool dateUpdatedFieldSpecified;
        
        private string deviceNameField;
        
        private bool isManualField;
        
        private bool isManualFieldSpecified;
        
        private bool isMatchedField;
        
        private bool isMatchedFieldSpecified;
        
        private string itemNumberField;
        
        private string locationField;
        
        private string palletField;
        
        private bool presentInStockField;
        
        private bool presentInStockFieldSpecified;
        
        private bool processByITField;
        
        private bool processByITFieldSpecified;
        
        private string productNameField;
        
        private string sizeField;
        
        private long syncIdField;
        
        private bool syncIdFieldSpecified;
        
        private string updatedByField;
        
        private string warehouseField;
        
        /// <remarks/>
        public decimal Available {
            get {
                return this.availableField;
            }
            set {
                this.availableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AvailableSpecified {
            get {
                return this.availableFieldSpecified;
            }
            set {
                this.availableFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BatchNumber {
            get {
                return this.batchNumberField;
            }
            set {
                this.batchNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateUpdated {
            get {
                return this.dateUpdatedField;
            }
            set {
                this.dateUpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateUpdatedSpecified {
            get {
                return this.dateUpdatedFieldSpecified;
            }
            set {
                this.dateUpdatedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeviceName {
            get {
                return this.deviceNameField;
            }
            set {
                this.deviceNameField = value;
            }
        }
        
        /// <remarks/>
        public bool IsManual {
            get {
                return this.isManualField;
            }
            set {
                this.isManualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsManualSpecified {
            get {
                return this.isManualFieldSpecified;
            }
            set {
                this.isManualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsMatched {
            get {
                return this.isMatchedField;
            }
            set {
                this.isMatchedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsMatchedSpecified {
            get {
                return this.isMatchedFieldSpecified;
            }
            set {
                this.isMatchedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pallet {
            get {
                return this.palletField;
            }
            set {
                this.palletField = value;
            }
        }
        
        /// <remarks/>
        public bool PresentInStock {
            get {
                return this.presentInStockField;
            }
            set {
                this.presentInStockField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PresentInStockSpecified {
            get {
                return this.presentInStockFieldSpecified;
            }
            set {
                this.presentInStockFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool ProcessByIT {
            get {
                return this.processByITField;
            }
            set {
                this.processByITField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcessByITSpecified {
            get {
                return this.processByITFieldSpecified;
            }
            set {
                this.processByITFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductName {
            get {
                return this.productNameField;
            }
            set {
                this.productNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public long SyncId {
            get {
                return this.syncIdField;
            }
            set {
                this.syncIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SyncIdSpecified {
            get {
                return this.syncIdFieldSpecified;
            }
            set {
                this.syncIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UpdatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Warehouse {
            get {
                return this.warehouseField;
            }
            set {
                this.warehouseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices")]
    public partial class UserData {
        
        private string passwordField;
        
        private string userNameField;
        
        private string userTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserType {
            get {
                return this.userTypeField;
            }
            set {
                this.userTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MulticastDelegate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyChangedEventHandler))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class Delegate {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PropertyChangedEventHandler))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System")]
    public partial class MulticastDelegate : Delegate {
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.ComponentModel")]
    public partial class PropertyChangedEventHandler : MulticastDelegate {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventAvailContract))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.InventCountingService")]
    public partial class XppObjectBase {
        
        private PropertyChangedEventHandler propertyChangedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PropertyChangedEventHandler PropertyChanged {
            get {
                return this.propertyChangedField;
            }
            set {
                this.propertyChangedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SyncServices.InventCountingService")]
    public partial class InventAvailContract : XppObjectBase {
        
        private decimal availPhysicalFieldField;
        
        private bool availPhysicalFieldSpecified1Field;
        
        private string batchIdFieldField;
        
        private string colorIdFieldField;
        
        private string configurationIdFieldField;
        
        private string itemIdFieldField;
        
        private string locationIdFieldField;
        
        private string productNameFieldField;
        
        private string serialIdFieldField;
        
        private string siteIdFieldField;
        
        private string sizeIdFieldField;
        
        private int syncIdFieldField;
        
        private bool syncIdFieldSpecified1Field;
        
        private string wMSLocationIdFieldField;
        
        /// <remarks/>
        public decimal availPhysicalField {
            get {
                return this.availPhysicalFieldField;
            }
            set {
                this.availPhysicalFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("availPhysicalFieldSpecified")]
        public bool availPhysicalFieldSpecified1 {
            get {
                return this.availPhysicalFieldSpecified1Field;
            }
            set {
                this.availPhysicalFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string batchIdField {
            get {
                return this.batchIdFieldField;
            }
            set {
                this.batchIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string colorIdField {
            get {
                return this.colorIdFieldField;
            }
            set {
                this.colorIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string configurationIdField {
            get {
                return this.configurationIdFieldField;
            }
            set {
                this.configurationIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string itemIdField {
            get {
                return this.itemIdFieldField;
            }
            set {
                this.itemIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string locationIdField {
            get {
                return this.locationIdFieldField;
            }
            set {
                this.locationIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string productNameField {
            get {
                return this.productNameFieldField;
            }
            set {
                this.productNameFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serialIdField {
            get {
                return this.serialIdFieldField;
            }
            set {
                this.serialIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string siteIdField {
            get {
                return this.siteIdFieldField;
            }
            set {
                this.siteIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sizeIdField {
            get {
                return this.sizeIdFieldField;
            }
            set {
                this.sizeIdFieldField = value;
            }
        }
        
        /// <remarks/>
        public int syncIdField {
            get {
                return this.syncIdFieldField;
            }
            set {
                this.syncIdFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("syncIdFieldSpecified")]
        public bool syncIdFieldSpecified1 {
            get {
                return this.syncIdFieldSpecified1Field;
            }
            set {
                this.syncIdFieldSpecified1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string wMSLocationIdField {
            get {
                return this.wMSLocationIdFieldField;
            }
            set {
                this.wMSLocationIdFieldField = value;
            }
        }
    }
}
